-- This query extracs
-- 1. Chloride exposure (mEq)
-- 2. Sodium exposure (mEq)
-- 3. Total fluid intake (ml)
-- for the first 24 hours after admission

-- volume_ml is obtained by sum all cellvaluenumeric
-- but only those that have a valid:
-- sodium_concentration or chloride_concentration (valid defined by Satoshi).

SELECT
patientunitstayid
,SUM(CASE
WHEN celllabel = '0.45 NS' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/100 mEq NaHCO3 1000 ml' THEN 177*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/20 mEq KCL' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/20 mEq KCL 1000 ml' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/40 mEq KCL' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/40 mEq KCL 1000 ml' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/75 mEq NaHCO3' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/75 mEq NaHCO3 1000 ml' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '0.9 NS_c' THEN 154*cellvaluenumeric/1000
WHEN celllabel = '0.9NS with 20mEq KCL_c' THEN 154*cellvaluenumeric/1000
WHEN celllabel = '1.5% NS' THEN 256.666667*cellvaluenumeric/1000
WHEN celllabel = '1.5% NaCl' THEN 256.666667*cellvaluenumeric/1000
WHEN celllabel = '1/2 NS' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '1/2NS + ADD' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '1/2NS + KCL' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '1/2NS IVF' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '3 Percent NaCl_c' THEN 513.333333*cellvaluenumeric/1000
WHEN celllabel = '3% saline' THEN 513.333333*cellvaluenumeric/1000
WHEN celllabel = 'D10' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D10 NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D10NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D10W' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D20W' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.2 NS' THEN 34.2222222*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/10 mEq KCL' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/20 mEq KCL' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/20 mEq KCL 1000 ml' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/20 mEq KCL and 10 mmol (as PO4) KPO4' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/40 mEq KCL' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/40 mEq KCL 1000 ml' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/75 mEq NaHCO3 1000 ml' THEN 152*cellvaluenumeric/1000
WHEN celllabel = 'D5 1/2 NS Volume' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 1/2 NS w/KCl 20mEq Volume' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 1/2NS' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 1/2NS + KCL' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 LR' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'D5 LR Volume' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'D5 NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5.45NS+KCl' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D51/2NS IVF' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D51/4NS IVF' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5LR IVF' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'D5NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS  w/150 mEq NaHCO3 1000 ml' THEN 304*cellvaluenumeric/1000
WHEN celllabel = 'D5NS  w/20 mEq KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS  w/20 mEq KCL 1000 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS  w/40 mEq KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS  w/40 mEq KCL 1000 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS + KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS Volume' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5W' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/ mEq NaHCO3' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/100 mEq NaHCO3 1000 ml' THEN 100*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/150 mEq NaHCO3' THEN 150*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/150 mEq NaHCO3 1000 ml' THEN 150*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/20 mEq KCL' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/20 mEq KCL 1000 ml' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/40 mEq KCL 1000 ml' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/50 mEq NaHCO3 1000 ml' THEN 50*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/60 mEq KCL 1000 ml' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/75 mEq NaHCO3 1000 ml' THEN 75*cellvaluenumeric/1000
WHEN celllabel = 'D5W + ADD' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'LR' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'LR' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'LR  w/20 mEq KCL 1000 ml' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'LR  w/40 mEq KCL' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'LR  w/40 mEq KCL 1000 ml' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'LR  w/60 mEq KCL 1000 ml' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'LR Bolus' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'LR IVF' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'LR bolus' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/ mEq KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/15 mmol (as PO4) KPO4 250 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/15 mmol (as PO4) NaPO4 250 ml' THEN 169*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/150 mEq NaHCO3 1000 ml' THEN 304*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/20 mEq KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/20 mEq KCL 1000 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/30 mmol (as PO4) KPO4' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/30 mmol (as PO4) KPO4 250 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/30 mmol (as PO4) KPO4 500 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/40 mEq KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/40 mEq KCL 1000 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/40 mEq KCL 500 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/45 mmol (as PO4) KPO4 1000 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/45 mmol (as PO4) KPO4 500 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/60 mEq KCL 1000 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS + ABX' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS + ADD' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS + Abx' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS + KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS 0.9% Volume' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS 1.5%' THEN 256.666667*cellvaluenumeric/1000
WHEN celllabel = 'NS @ KVO' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS Addits' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS BOLUS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS Bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS KVO' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS TKO' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS b IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS c IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS d IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS e IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS flushes' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS for Blood Administration' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS w/ abx' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS w/KCl 20mEq Volume' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS with 20KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS+KCl' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS+abx' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS/abx' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NaCl 1.5%' THEN 256.666667*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.45 % NaCl with KCl 20 mEq / L infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.45 % sodium chloride infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.45 % sodium chloride solution' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.45 % sodium chloride with KCl 20 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9 %  sodium chloride infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9 % NaCl with KCl 20 mEq/ L  infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9 % NaCl with KCl 40 mEq / L  infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9 % sodium chloride solution' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9 % sodium chloride with potassium chloride 20 mEq/L infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9% sodium chloride with potassium chloride 40 mEq/L infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-Ampicillin-Sulbactam (UNASYN) 3 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-Dextran 40 in sodium chloride (DEXTRAN 40 IN NS) 10-0.9 % infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-Micafungin Sodium 100 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-SODIUM CHLORIDE 0.9 % IV SOLN' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-SODIUM CHLORIDE 0.9 % IV SOLN Pyxis Override' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 12 g in sodium chloride 0.9 % 500 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 2 g in sodium chloride 0.9 % 50 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin-sulbactam (UNASYN) 1.5 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin-sulbactam (UNASYN) 1.5 g in sodium chloride 0.9 % 50 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin-sulbactam (UNASYN) 3 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-azithromycin (ZITHROMAX) 500 mg in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-azithromycin (ZITHROMAX) 500 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 1 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 2 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-calcium chloride 100 mEq in sodium chloride 0.9 % 1,000 mL infusion (CRRT with citrate anticoag)' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-calcium gluconate 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-calcium gluconate 2 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFAZolin (ANCEF) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFAZolin (ANCEF) in d5w 2 g premix' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFAZolin 2,000 mg in sodium chloride 0.9% 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 1 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 2 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTAZidime (FORTAZ) 1 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTAZidime (FORTAZ) 2 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 1 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 2 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefUROXime (ZINACEF) 1.5 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefepime (MAXIPIME) 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefepime (MAXIPIME) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ciprofloxacin (CIPRO) 400 mg in dextrose 5% 200 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-clindamycin 600 mg in sodium chloride 0.9% 50 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-clindamycin 900 mg in sodium chloride 0.9% 50 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextran 40 in dextrose 5% (DEXTRAN 40 IN D5W) 10 % infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 10 % infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / lactated ringers infusion' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% 1,000 mL with magnesium sulfate 5 g infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% 1,000 mL with potassium chloride 40 mEq, magnesium sulfate 5 g infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% with KCl 20 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% with KCl 40 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.9% infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.9% with KCl 20 mEq infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 20 mEq infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 40 mEq infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 100 mEq infusion' THEN 100*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 150 mEq infusion' THEN 150*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 50 mEq infusion' THEN 50*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2 % NaCl infusion' THEN 34.2222222*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2 % sodium chloride 1,000 mL with sodium bicarbonate 100 mEq infusion' THEN 132*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2 % sodium chloride infusion' THEN 34.2222222*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2% sodium chloride infusion' THEN 34.2222222*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 10 mEq/L infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 20 mEq/L infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 30 mEq/L infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 40 mEq/L infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % sodium chloride with KCl 20 mEq/L infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % sodium chloride with KCl 40 mEq/L infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% NaCl 1,000 mL with potassium chloride 20 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% NaCl infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% sodium chloride 1,000 mL with sodium bicarbonate 50 mEq infusion' THEN 127*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% sodium chloride 1,000 mL with sodium bicarbonate 75 mEq infusion' THEN 152*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 20 mEq/L infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 40 mEq/L infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9 % sodium chloride with KCl 20 mEq/L' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9% NaCl 1,000 mL with potassium chloride 20 mEq infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9% NaCl infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9% sodium chloride 1,000 mL with potassium chloride 40 mEq infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % in lactated ringers infusion' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % solution' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % with KCl 20 mEq / L  infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 %-0.45 % sodium chloride infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 %-0.9 % sodium chloride infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-doxycycline (VIBRAMYCIN) 100 mg in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-doxycycline (VIBRAMYCIN) 100 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-erythromycin (ERYTHROCIN) 250 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-furosemide (LASIX) 120 mg in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-furosemide (LASIX) 160 mg in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-hydrocortisone sod succ PF (Solu-CORTEF) 250 mg in sodium chloride 0.9 % 250 mL infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-imipenem-cilastatin (PRIMAXIN) 250 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-imipenem-cilastatin (PRIMAXIN) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers 1,000 mL with potassium chloride 20 mEq infusion' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers 1,000 mL with thiamine 100 mg, folic acid 1 mg, magnesium sulfate 2 g infusion' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers bolus 1,000 mL' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers bolus 500 mL' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers infusion' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers infusion 1,000 mL' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers infusion 500 mL' THEN 130*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 1,500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 250 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 750 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levofloxacin (LEVAQUIN) in dextrose 5% premix IVPB 500 mg' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levofloxacin (LEVAQUIN) in dextrose 5% premix IVPB 750 mg' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-magnesium sulfate 1 g in dextrose 5% 100 mL IVPB premix' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-magnesium sulfate 2 g in sodium chloride 0.9% IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-magnesium sulfate in 5 % dextrose IVPB 1 g' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-meropenem (MERREM) 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-meropenem (MERREM) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-meropenem (MERREM) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-micafungin (MYCAMINE) 100 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-micafungin 100 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-nafcillin (NAFCIL) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ondansetron (ZOFRAN) 8 mg/NS 50 ml IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 2.25 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL EXTENDED INFUSION IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL FOUR HOUR EXTENDED INFUSION IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL thirty minute IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 4.5 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 4.5 g in sodium chloride 0.9 % 100 mL thirty minute IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-potassium phosphate 10 mmol in dextrose 5 % 250 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-potassium phosphate 15 mmol in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-potassium phosphate 20 mmol in dextrose 5 % 500 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-potassium phosphate 30 mmol in dextrose 5 % 500 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 100 mEq in dextrose 5 % 1,000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5 % 1,000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5% 1000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 150 mEq in sterile water 1,000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 50 mEq in dextrose 5 % 1,000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 75 mEq in dextrose 5 % 1,000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 1,000 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 250 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 500 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride (hypertonic) 3 % solution' THEN 513.333333*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.225 % with sodium bicarbonate 100 mEq infusion' THEN 138.5*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with potassium chloride 40 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 100 mEq infusion' THEN 177*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 50 mEq infusion' THEN 127*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 75 mEq infusion' THEN 152*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % with KCl 20 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL IV bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 10 mEq infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 20 mEq infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 40 mEq infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with thiamine 100 mg, folic acid 1 mg, multivitamins adult 1 mL infusion' THEN 1540*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 2,000 mL IV bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 250 mL IV bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 500 mL IV bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % bolus 1,000 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % bolus 250 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % bolus 500 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % flush IVPB 250 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % flush IVPB 500 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % with KCl 20 mEq infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % with KCl 40 mEq infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9% infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 3 % solution' THEN 513.333333*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium glycerophosphate (GLYCOPHOS) 10 mmol in sodium chloride 0.9 % 250 mL infusion' THEN 164*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium glycerophosphate (GLYCOPHOS) 20 mmol in sodium chloride 0.9 % 250 mL infusion' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium phosphate 10 mmol in dextrose 5 % 250 mL infusion' THEN 30*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium phosphate 15 mmol in dextrose 5 % 250 mL IVPB' THEN 45*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium phosphate 20 mmol in dextrose 5 % 250 mL IVPB' THEN 60*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium phosphate 20 mmol in dextrose 5 % 250 mL infusion' THEN 60*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium phosphate 30 mmol in dextrose 5 % 250 mL infusion' THEN 90*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-tigecycline (TYGACIL) 50 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-tranexamic acid 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-valproate (DEPACON) 500 mg in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-valproate (DEPACON) 500 mg in sodium chloride 0.9 % 50 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,000 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,250 mg in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,250 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in sodium chloride 0.9 % 500 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,750 mg in dextrose 5 % 500 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,750 mg in sodium chloride 0.9 % 500 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 2,000 mg in sodium chloride 0.9 % 500 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 750 mg in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 750 mg in sodium chloride 0.9 % 150 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 750 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin 1,250 mg in sodium chloride 0.9% 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin 1,500 mg in sodium chloride 0.9% 250 mL IVPB' THEN 154*cellvaluenumeric/1000
END) AS total_na_meq_day1
,SUM(CASE
WHEN celllabel = '0.45 NS' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/100 mEq NaHCO3 1000 ml' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/20 mEq KCL' THEN 79*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/20 mEq KCL 1000 ml' THEN 79*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/40 mEq KCL' THEN 119*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/40 mEq KCL 1000 ml' THEN 119*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/75 mEq NaHCO3' THEN 122*cellvaluenumeric/1000
WHEN celllabel = '0.45 NS  w/75 mEq NaHCO3 1000 ml' THEN 122*cellvaluenumeric/1000
WHEN celllabel = '0.9 NS_c' THEN 154*cellvaluenumeric/1000
WHEN celllabel = '0.9NS with 20mEq KCL_c' THEN 174*cellvaluenumeric/1000
WHEN celllabel = '1.5% NS' THEN 256.666667*cellvaluenumeric/1000
WHEN celllabel = '1.5% NaCl' THEN 256.666667*cellvaluenumeric/1000
WHEN celllabel = '1/2 NS' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '1/2NS + ADD' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '1/2NS + KCL' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '1/2NS IVF' THEN 77*cellvaluenumeric/1000
WHEN celllabel = '3 Percent NaCl_c' THEN 513.333333*cellvaluenumeric/1000
WHEN celllabel = '3% saline' THEN 513.333333*cellvaluenumeric/1000
WHEN celllabel = 'D10' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D10 NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D10NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D10W' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D20W' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.2 NS' THEN 34.2222222*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/10 mEq KCL' THEN 87*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/20 mEq KCL' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/20 mEq KCL 1000 ml' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/20 mEq KCL and 10 mmol (as PO4) KPO4' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/40 mEq KCL' THEN 114*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/40 mEq KCL 1000 ml' THEN 114*cellvaluenumeric/1000
WHEN celllabel = 'D5 0.45 NS  w/75 mEq NaHCO3 1000 ml' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 1/2 NS Volume' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 1/2 NS w/KCl 20mEq Volume' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'D5 1/2NS' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 1/2NS + KCL' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5 LR' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'D5 LR Volume' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'D5 NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5.45NS+KCl' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D51/2NS IVF' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D51/4NS IVF' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'D5LR IVF' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'D5NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS  w/150 mEq NaHCO3 1000 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS  w/20 mEq KCL' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'D5NS  w/20 mEq KCL 1000 ml' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'D5NS  w/40 mEq KCL' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'D5NS  w/40 mEq KCL 1000 ml' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'D5NS + KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5NS Volume' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'D5W' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/ mEq NaHCO3' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/100 mEq NaHCO3 1000 ml' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/150 mEq NaHCO3' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/150 mEq NaHCO3 1000 ml' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/20 mEq KCL' THEN 20*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/20 mEq KCL 1000 ml' THEN 20*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/40 mEq KCL 1000 ml' THEN 40*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/50 mEq NaHCO3 1000 ml' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/60 mEq KCL 1000 ml' THEN 60*cellvaluenumeric/1000
WHEN celllabel = 'D5W  w/75 mEq NaHCO3 1000 ml' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'D5W + ADD' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'LR' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'LR' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'LR  w/20 mEq KCL 1000 ml' THEN 129*cellvaluenumeric/1000
WHEN celllabel = 'LR  w/40 mEq KCL' THEN 149*cellvaluenumeric/1000
WHEN celllabel = 'LR  w/40 mEq KCL 1000 ml' THEN 149*cellvaluenumeric/1000
WHEN celllabel = 'LR  w/60 mEq KCL 1000 ml' THEN 169*cellvaluenumeric/1000
WHEN celllabel = 'LR Bolus' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'LR IVF' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'LR bolus' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/ mEq KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/15 mmol (as PO4) KPO4 250 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/15 mmol (as PO4) NaPO4 250 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/150 mEq NaHCO3 1000 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/20 mEq KCL' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/20 mEq KCL 1000 ml' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/30 mmol (as PO4) KPO4' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/30 mmol (as PO4) KPO4 250 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/30 mmol (as PO4) KPO4 500 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/40 mEq KCL' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/40 mEq KCL 1000 ml' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/40 mEq KCL 500 ml' THEN 234*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/45 mmol (as PO4) KPO4 1000 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/45 mmol (as PO4) KPO4 500 ml' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS  w/60 mEq KCL 1000 ml' THEN 214*cellvaluenumeric/1000
WHEN celllabel = 'NS + ABX' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS + ADD' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS + Abx' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS + KCL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS 0.9% Volume' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS 1.5%' THEN 256.666667*cellvaluenumeric/1000
WHEN celllabel = 'NS @ KVO' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS Addits' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS BOLUS' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS Bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS KVO' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS TKO' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS b IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS c IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS d IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS e IVF' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS flushes' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS for Blood Administration' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS w/ abx' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS w/KCl 20mEq Volume' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'NS with 20KCL' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'NS+KCl' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS+abx' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NS/abx' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'NaCl 1.5%' THEN 256.666667*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.45 % NaCl with KCl 20 mEq / L infusion' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.45 % sodium chloride infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.45 % sodium chloride solution' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.45 % sodium chloride with KCl 20 mEq infusion' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9 %  sodium chloride infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9 % NaCl with KCl 20 mEq/ L  infusion' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9 % NaCl with KCl 40 mEq / L  infusion' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9 % sodium chloride solution' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9 % sodium chloride with potassium chloride 20 mEq/L infusion' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-0.9% sodium chloride with potassium chloride 40 mEq/L infusion' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-Ampicillin-Sulbactam (UNASYN) 3 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-Dextran 40 in sodium chloride (DEXTRAN 40 IN NS) 10-0.9 % infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-Micafungin Sodium 100 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-SODIUM CHLORIDE 0.9 % IV SOLN' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-SODIUM CHLORIDE 0.9 % IV SOLN Pyxis Override' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 12 g in sodium chloride 0.9 % 500 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 2 g in sodium chloride 0.9 % 50 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin-sulbactam (UNASYN) 1.5 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin-sulbactam (UNASYN) 1.5 g in sodium chloride 0.9 % 50 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ampicillin-sulbactam (UNASYN) 3 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-azithromycin (ZITHROMAX) 500 mg in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-azithromycin (ZITHROMAX) 500 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 1 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 2 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-calcium chloride 100 mEq in sodium chloride 0.9 % 1,000 mL infusion (CRRT with citrate anticoag)' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-calcium gluconate 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-calcium gluconate 2 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFAZolin (ANCEF) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFAZolin (ANCEF) in d5w 2 g premix' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFAZolin 2,000 mg in sodium chloride 0.9% 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 1 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 2 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTAZidime (FORTAZ) 1 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTAZidime (FORTAZ) 2 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 1 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 2 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefUROXime (ZINACEF) 1.5 g in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefepime (MAXIPIME) 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-cefepime (MAXIPIME) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ciprofloxacin (CIPRO) 400 mg in dextrose 5% 200 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-clindamycin 600 mg in sodium chloride 0.9% 50 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-clindamycin 900 mg in sodium chloride 0.9% 50 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextran 40 in dextrose 5% (DEXTRAN 40 IN D5W) 10 % infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 10 % infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / lactated ringers infusion' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% 1,000 mL with magnesium sulfate 5 g infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% 1,000 mL with potassium chloride 40 mEq, magnesium sulfate 5 g infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% with KCl 20 mEq infusion' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% with KCl 40 mEq infusion' THEN 117*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.9% infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.9% with KCl 20 mEq infusion' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 20 mEq infusion' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 40 mEq infusion' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 100 mEq infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 150 mEq infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 50 mEq infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2 % NaCl infusion' THEN 34.2222222*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2 % sodium chloride 1,000 mL with sodium bicarbonate 100 mEq infusion' THEN 34.2222222*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2 % sodium chloride infusion' THEN 34.2222222*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2% sodium chloride infusion' THEN 34.2222222*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 10 mEq/L infusion' THEN 87*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 20 mEq/L infusion' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 30 mEq/L infusion' THEN 107*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 40 mEq/L infusion' THEN 117*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % sodium chloride with KCl 20 mEq/L infusion' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % sodium chloride with KCl 40 mEq/L infusion' THEN 117*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% NaCl 1,000 mL with potassium chloride 20 mEq infusion' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% NaCl infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% sodium chloride 1,000 mL with sodium bicarbonate 50 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% sodium chloride 1,000 mL with sodium bicarbonate 75 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 20 mEq/L infusion' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 40 mEq/L infusion' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9 % sodium chloride with KCl 20 mEq/L' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9% NaCl 1,000 mL with potassium chloride 20 mEq infusion' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9% NaCl infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9% sodium chloride 1,000 mL with potassium chloride 40 mEq infusion' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % in lactated ringers infusion' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % solution' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 % with KCl 20 mEq / L  infusion' THEN 20*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 %-0.45 % sodium chloride infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-dextrose 5 %-0.9 % sodium chloride infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-doxycycline (VIBRAMYCIN) 100 mg in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-doxycycline (VIBRAMYCIN) 100 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-erythromycin (ERYTHROCIN) 250 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-furosemide (LASIX) 120 mg in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-furosemide (LASIX) 160 mg in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-hydrocortisone sod succ PF (Solu-CORTEF) 250 mg in sodium chloride 0.9 % 250 mL infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-imipenem-cilastatin (PRIMAXIN) 250 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-imipenem-cilastatin (PRIMAXIN) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers 1,000 mL with potassium chloride 20 mEq infusion' THEN 129*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers 1,000 mL with thiamine 100 mg, folic acid 1 mg, magnesium sulfate 2 g infusion' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers bolus 1,000 mL' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers bolus 500 mL' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers infusion' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers infusion 1,000 mL' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-lactated ringers infusion 500 mL' THEN 109*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 1,500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 250 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 750 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levofloxacin (LEVAQUIN) in dextrose 5% premix IVPB 500 mg' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-levofloxacin (LEVAQUIN) in dextrose 5% premix IVPB 750 mg' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-magnesium sulfate 1 g in dextrose 5% 100 mL IVPB premix' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-magnesium sulfate 2 g in sodium chloride 0.9% IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-magnesium sulfate in 5 % dextrose IVPB 1 g' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-meropenem (MERREM) 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-meropenem (MERREM) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-meropenem (MERREM) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-micafungin (MYCAMINE) 100 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-micafungin 100 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-nafcillin (NAFCIL) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-ondansetron (ZOFRAN) 8 mg/NS 50 ml IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 2.25 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL EXTENDED INFUSION IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL FOUR HOUR EXTENDED INFUSION IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL thirty minute IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 4.5 g in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 4.5 g in sodium chloride 0.9 % 100 mL thirty minute IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-potassium phosphate 10 mmol in dextrose 5 % 250 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-potassium phosphate 15 mmol in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-potassium phosphate 20 mmol in dextrose 5 % 500 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-potassium phosphate 30 mmol in dextrose 5 % 500 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 100 mEq in dextrose 5 % 1,000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5 % 1,000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5% 1000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 150 mEq in sterile water 1,000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 50 mEq in dextrose 5 % 1,000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 75 mEq in dextrose 5 % 1,000 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 1,000 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 250 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 500 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride (hypertonic) 3 % solution' THEN 513.333333*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.225 % with sodium bicarbonate 100 mEq infusion' THEN 38.5*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with potassium chloride 40 mEq infusion' THEN 117*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 100 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 50 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 75 mEq infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % infusion' THEN 77*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % with KCl 20 mEq infusion' THEN 97*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL IV bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 10 mEq infusion' THEN 164*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 20 mEq infusion' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 40 mEq infusion' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with thiamine 100 mg, folic acid 1 mg, multivitamins adult 10 mL infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 2,000 mL IV bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 250 mL IV bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 500 mL IV bolus' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % bolus 1,000 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % bolus 250 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % bolus 500 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % flush IVPB 250 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % flush IVPB 500 mL' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % with KCl 20 mEq infusion' THEN 174*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % with KCl 40 mEq infusion' THEN 194*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9% infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium chloride 3 % solution' THEN 513.333333*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium glycerophosphate (GLYCOPHOS) 10 mmol in sodium chloride 0.9 % 250 mL infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium glycerophosphate (GLYCOPHOS) 20 mmol in sodium chloride 0.9 % 250 mL infusion' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium phosphate 10 mmol in dextrose 5 % 250 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium phosphate 15 mmol in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium phosphate 20 mmol in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium phosphate 20 mmol in dextrose 5 % 250 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-sodium phosphate 30 mmol in dextrose 5 % 250 mL infusion' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-tigecycline (TYGACIL) 50 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-tranexamic acid 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-valproate (DEPACON) 500 mg in dextrose 5 % 50 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-valproate (DEPACON) 500 mg in sodium chloride 0.9 % 50 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,000 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,250 mg in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,250 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in sodium chloride 0.9 % 500 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,750 mg in dextrose 5 % 500 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,750 mg in sodium chloride 0.9 % 500 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 2,000 mg in sodium chloride 0.9 % 500 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 750 mg in dextrose 5 % 250 mL IVPB' THEN 0*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 750 mg in sodium chloride 0.9 % 150 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 750 mg in sodium chloride 0.9 % 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin 1,250 mg in sodium chloride 0.9% 250 mL IVPB' THEN 154*cellvaluenumeric/1000
WHEN celllabel = 'Volume (mL)-vancomycin 1,500 mg in sodium chloride 0.9% 250 mL IVPB' THEN 154*cellvaluenumeric/1000
END) AS total_cl_meq_day1
,SUM(CASE
WHEN celllabel = '0.45 NS' THEN cellvaluenumeric 
WHEN celllabel = '0.45 NS  w/100 mEq NaHCO3 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = '0.45 NS  w/20 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = '0.45 NS  w/20 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = '0.45 NS  w/40 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = '0.45 NS  w/40 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = '0.45 NS  w/75 mEq NaHCO3' THEN cellvaluenumeric 
WHEN celllabel = '0.45 NS  w/75 mEq NaHCO3 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = '0.9 NS_c' THEN cellvaluenumeric 
WHEN celllabel = '0.9NS with 20mEq KCL_c' THEN cellvaluenumeric 
WHEN celllabel = '1.5% NS' THEN cellvaluenumeric 
WHEN celllabel = '1.5% NaCl' THEN cellvaluenumeric 
WHEN celllabel = '1/2 NS' THEN cellvaluenumeric 
WHEN celllabel = '1/2NS + ADD' THEN cellvaluenumeric 
WHEN celllabel = '1/2NS + KCL' THEN cellvaluenumeric 
WHEN celllabel = '1/2NS IVF' THEN cellvaluenumeric 
WHEN celllabel = '3 Percent NaCl_c' THEN cellvaluenumeric 
WHEN celllabel = '3% saline' THEN cellvaluenumeric 
WHEN celllabel = 'D10' THEN cellvaluenumeric 
WHEN celllabel = 'D10 NS' THEN cellvaluenumeric 
WHEN celllabel = 'D10NS' THEN cellvaluenumeric 
WHEN celllabel = 'D10W' THEN cellvaluenumeric 
WHEN celllabel = 'D20W' THEN cellvaluenumeric 
WHEN celllabel = 'D5 0.2 NS' THEN cellvaluenumeric 
WHEN celllabel = 'D5 0.45 NS' THEN cellvaluenumeric 
WHEN celllabel = 'D5 0.45 NS  w/10 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = 'D5 0.45 NS  w/20 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = 'D5 0.45 NS  w/20 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5 0.45 NS  w/20 mEq KCL and 10 mmol (as PO4) KPO4' THEN cellvaluenumeric 
WHEN celllabel = 'D5 0.45 NS  w/40 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = 'D5 0.45 NS  w/40 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5 0.45 NS  w/75 mEq NaHCO3 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5 1/2 NS Volume' THEN cellvaluenumeric 
WHEN celllabel = 'D5 1/2 NS w/KCl 20mEq Volume' THEN cellvaluenumeric 
WHEN celllabel = 'D5 1/2NS' THEN cellvaluenumeric 
WHEN celllabel = 'D5 1/2NS + KCL' THEN cellvaluenumeric 
WHEN celllabel = 'D5 LR' THEN cellvaluenumeric 
WHEN celllabel = 'D5 LR Volume' THEN cellvaluenumeric 
WHEN celllabel = 'D5 NS' THEN cellvaluenumeric 
WHEN celllabel = 'D5.45NS+KCl' THEN cellvaluenumeric 
WHEN celllabel = 'D51/2NS IVF' THEN cellvaluenumeric 
WHEN celllabel = 'D51/4NS IVF' THEN cellvaluenumeric 
WHEN celllabel = 'D5LR IVF' THEN cellvaluenumeric 
WHEN celllabel = 'D5NS' THEN cellvaluenumeric 
WHEN celllabel = 'D5NS' THEN cellvaluenumeric 
WHEN celllabel = 'D5NS  w/150 mEq NaHCO3 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5NS  w/20 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = 'D5NS  w/20 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5NS  w/40 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = 'D5NS  w/40 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5NS + KCL' THEN cellvaluenumeric 
WHEN celllabel = 'D5NS IVF' THEN cellvaluenumeric 
WHEN celllabel = 'D5NS Volume' THEN cellvaluenumeric 
WHEN celllabel = 'D5W' THEN cellvaluenumeric 
WHEN celllabel = 'D5W' THEN cellvaluenumeric 
WHEN celllabel = 'D5W  w/ mEq NaHCO3' THEN cellvaluenumeric 
WHEN celllabel = 'D5W  w/100 mEq NaHCO3 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5W  w/150 mEq NaHCO3' THEN cellvaluenumeric 
WHEN celllabel = 'D5W  w/150 mEq NaHCO3 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5W  w/20 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = 'D5W  w/20 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5W  w/40 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5W  w/50 mEq NaHCO3 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5W  w/60 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5W  w/75 mEq NaHCO3 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'D5W + ADD' THEN cellvaluenumeric 
WHEN celllabel = 'LR' THEN cellvaluenumeric 
WHEN celllabel = 'LR' THEN cellvaluenumeric 
WHEN celllabel = 'LR  w/20 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'LR  w/40 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = 'LR  w/40 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'LR  w/60 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'LR Bolus' THEN cellvaluenumeric 
WHEN celllabel = 'LR IVF' THEN cellvaluenumeric 
WHEN celllabel = 'LR bolus' THEN cellvaluenumeric 
WHEN celllabel = 'NS' THEN cellvaluenumeric 
WHEN celllabel = 'NS' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/ mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/15 mmol (as PO4) KPO4 250 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/15 mmol (as PO4) NaPO4 250 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/150 mEq NaHCO3 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/20 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/20 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/30 mmol (as PO4) KPO4' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/30 mmol (as PO4) KPO4 250 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/30 mmol (as PO4) KPO4 500 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/40 mEq KCL' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/40 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/40 mEq KCL 500 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/45 mmol (as PO4) KPO4 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/45 mmol (as PO4) KPO4 500 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS  w/60 mEq KCL 1000 ml' THEN cellvaluenumeric 
WHEN celllabel = 'NS + ABX' THEN cellvaluenumeric 
WHEN celllabel = 'NS + ADD' THEN cellvaluenumeric 
WHEN celllabel = 'NS + Abx' THEN cellvaluenumeric 
WHEN celllabel = 'NS + KCL' THEN cellvaluenumeric 
WHEN celllabel = 'NS 0.9% Volume' THEN cellvaluenumeric 
WHEN celllabel = 'NS 1.5%' THEN cellvaluenumeric 
WHEN celllabel = 'NS @ KVO' THEN cellvaluenumeric 
WHEN celllabel = 'NS Addits' THEN cellvaluenumeric 
WHEN celllabel = 'NS BOLUS' THEN cellvaluenumeric 
WHEN celllabel = 'NS Bolus' THEN cellvaluenumeric 
WHEN celllabel = 'NS IVF' THEN cellvaluenumeric 
WHEN celllabel = 'NS KVO' THEN cellvaluenumeric 
WHEN celllabel = 'NS TKO' THEN cellvaluenumeric 
WHEN celllabel = 'NS b IVF' THEN cellvaluenumeric 
WHEN celllabel = 'NS bolus' THEN cellvaluenumeric 
WHEN celllabel = 'NS c IVF' THEN cellvaluenumeric 
WHEN celllabel = 'NS d IVF' THEN cellvaluenumeric 
WHEN celllabel = 'NS e IVF' THEN cellvaluenumeric 
WHEN celllabel = 'NS flushes' THEN cellvaluenumeric 
WHEN celllabel = 'NS for Blood Administration' THEN cellvaluenumeric 
WHEN celllabel = 'NS w/ abx' THEN cellvaluenumeric 
WHEN celllabel = 'NS w/KCl 20mEq Volume' THEN cellvaluenumeric 
WHEN celllabel = 'NS with 20KCL' THEN cellvaluenumeric 
WHEN celllabel = 'NS+KCl' THEN cellvaluenumeric 
WHEN celllabel = 'NS+abx' THEN cellvaluenumeric 
WHEN celllabel = 'NS/abx' THEN cellvaluenumeric 
WHEN celllabel = 'NaCl 1.5%' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-0.45 % NaCl with KCl 20 mEq / L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-0.45 % sodium chloride infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-0.45 % sodium chloride solution' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-0.45 % sodium chloride with KCl 20 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-0.9 %  sodium chloride infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-0.9 % NaCl with KCl 20 mEq/ L  infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-0.9 % NaCl with KCl 40 mEq / L  infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-0.9 % sodium chloride solution' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-0.9 % sodium chloride with potassium chloride 20 mEq/L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-0.9% sodium chloride with potassium chloride 40 mEq/L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-Ampicillin-Sulbactam (UNASYN) 3 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-Dextran 40 in sodium chloride (DEXTRAN 40 IN NS) 10-0.9 % infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-Micafungin Sodium 100 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-SODIUM CHLORIDE 0.9 % IV SOLN' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-SODIUM CHLORIDE 0.9 % IV SOLN Pyxis Override' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 12 g in sodium chloride 0.9 % 500 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 2 g in sodium chloride 0.9 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ampicillin (OMNIPEN) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ampicillin-sulbactam (UNASYN) 1.5 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ampicillin-sulbactam (UNASYN) 1.5 g in sodium chloride 0.9 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ampicillin-sulbactam (UNASYN) 3 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-azithromycin (ZITHROMAX) 500 mg in dextrose 5 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-azithromycin (ZITHROMAX) 500 mg in sodium chloride 0.9 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 1 g in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 2 g in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-aztreonam (AZACTAM) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-calcium chloride 100 mEq in sodium chloride 0.9 % 1,000 mL infusion (CRRT with citrate anticoag)' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-calcium gluconate 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-calcium gluconate 2 g in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ceFAZolin (ANCEF) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ceFAZolin (ANCEF) in d5w 2 g premix' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ceFAZolin 2,000 mg in sodium chloride 0.9% 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 1 g in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 2 g in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ceFEPIme (MAXIPIME) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefTAZidime (FORTAZ) 1 g in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefTAZidime (FORTAZ) 2 g in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 1 g in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 2 g in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefTRIAXone (ROCEPHIN) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefUROXime (ZINACEF) 1.5 g in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefepime (MAXIPIME) 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-cefepime (MAXIPIME) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ciprofloxacin (CIPRO) 400 mg in dextrose 5% 200 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-clindamycin 600 mg in sodium chloride 0.9% 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-clindamycin 900 mg in sodium chloride 0.9% 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextran 40 in dextrose 5% (DEXTRAN 40 IN D5W) 10 % infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 10 % infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % / lactated ringers infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% 1,000 mL with magnesium sulfate 5 g infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% 1,000 mL with potassium chloride 40 mEq, magnesium sulfate 5 g infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% with KCl 20 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.45% with KCl 40 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.9% infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % / sodium chloride 0.9% with KCl 20 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 20 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 40 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 100 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 150 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 50 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2 % NaCl infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2 % sodium chloride 1,000 mL with sodium bicarbonate 100 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2 % sodium chloride infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.2% sodium chloride infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 10 mEq/L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 20 mEq/L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 30 mEq/L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 40 mEq/L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % sodium chloride with KCl 20 mEq/L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45 % sodium chloride with KCl 40 mEq/L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% NaCl 1,000 mL with potassium chloride 20 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% NaCl infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% sodium chloride 1,000 mL with sodium bicarbonate 50 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.45% sodium chloride 1,000 mL with sodium bicarbonate 75 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 20 mEq/L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 40 mEq/L infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9 % sodium chloride with KCl 20 mEq/L' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9% NaCl 1,000 mL with potassium chloride 20 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9% NaCl infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % and 0.9% sodium chloride 1,000 mL with potassium chloride 40 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % in lactated ringers infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % solution' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 % with KCl 20 mEq / L  infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 %-0.45 % sodium chloride infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-dextrose 5 %-0.9 % sodium chloride infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-doxycycline (VIBRAMYCIN) 100 mg in dextrose 5 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-doxycycline (VIBRAMYCIN) 100 mg in sodium chloride 0.9 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-erythromycin (ERYTHROCIN) 250 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-furosemide (LASIX) 120 mg in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-furosemide (LASIX) 160 mg in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-hydrocortisone sod succ PF (Solu-CORTEF) 250 mg in sodium chloride 0.9 % 250 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-imipenem-cilastatin (PRIMAXIN) 250 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-imipenem-cilastatin (PRIMAXIN) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-lactated ringers 1,000 mL with potassium chloride 20 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-lactated ringers 1,000 mL with thiamine 100 mg, folic acid 1 mg, magnesium sulfate 2 g infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-lactated ringers bolus 1,000 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-lactated ringers bolus 500 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-lactated ringers infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-lactated ringers infusion 1,000 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-lactated ringers infusion 500 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 1,500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 250 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-levETIRAcetam (KEPPRA) 750 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-levofloxacin (LEVAQUIN) in dextrose 5% premix IVPB 500 mg' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-levofloxacin (LEVAQUIN) in dextrose 5% premix IVPB 750 mg' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-magnesium sulfate 1 g in dextrose 5% 100 mL IVPB premix' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-magnesium sulfate 2 g in sodium chloride 0.9% IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-magnesium sulfate in 5 % dextrose IVPB 1 g' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-meropenem (MERREM) 1 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-meropenem (MERREM) 2 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-meropenem (MERREM) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-micafungin (MYCAMINE) 100 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-micafungin 100 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-nafcillin (NAFCIL) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-ondansetron (ZOFRAN) 8 mg/NS 50 ml IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 2.25 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL EXTENDED INFUSION IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL FOUR HOUR EXTENDED INFUSION IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL thirty minute IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 4.5 g in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-piperacillin-tazobactam (ZOSYN) 4.5 g in sodium chloride 0.9 % 100 mL thirty minute IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-potassium phosphate 10 mmol in dextrose 5 % 250 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-potassium phosphate 15 mmol in dextrose 5 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-potassium phosphate 20 mmol in dextrose 5 % 500 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-potassium phosphate 30 mmol in dextrose 5 % 500 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 100 mEq in dextrose 5 % 1,000 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5 % 1,000 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5% 1000 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 150 mEq in sterile water 1,000 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 50 mEq in dextrose 5 % 1,000 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium bicarbonate 75 mEq in dextrose 5 % 1,000 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 1,000 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 250 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 500 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride (hypertonic) 3 % solution' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.225 % with sodium bicarbonate 100 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with potassium chloride 40 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 100 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 50 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 75 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.45 % with KCl 20 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL IV bolus' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 10 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 20 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 40 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 1,000 mL with thiamine 100 mg, folic acid 1 mg, multivitamins adult 10 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 2,000 mL IV bolus' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 250 mL IV bolus' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % 500 mL IV bolus' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % bolus 1,000 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % bolus 250 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % bolus 500 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % flush IVPB 250 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % flush IVPB 500 mL' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % with KCl 20 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9 % with KCl 40 mEq infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 0.9% infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium chloride 3 % solution' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium glycerophosphate (GLYCOPHOS) 10 mmol in sodium chloride 0.9 % 250 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium glycerophosphate (GLYCOPHOS) 20 mmol in sodium chloride 0.9 % 250 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium phosphate 10 mmol in dextrose 5 % 250 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium phosphate 15 mmol in dextrose 5 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium phosphate 20 mmol in dextrose 5 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium phosphate 20 mmol in dextrose 5 % 250 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-sodium phosphate 30 mmol in dextrose 5 % 250 mL infusion' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-tigecycline (TYGACIL) 50 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-tranexamic acid 1,000 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-valproate (DEPACON) 500 mg in dextrose 5 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-valproate (DEPACON) 500 mg in sodium chloride 0.9 % 50 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,000 mg in sodium chloride 0.9 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,250 mg in dextrose 5 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,250 mg in sodium chloride 0.9 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in dextrose 5 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in sodium chloride 0.9 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in sodium chloride 0.9 % 500 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,750 mg in dextrose 5 % 500 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 1,750 mg in sodium chloride 0.9 % 500 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 2,000 mg in sodium chloride 0.9 % 500 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 500 mg in sodium chloride 0.9 % 100 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 750 mg in dextrose 5 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 750 mg in sodium chloride 0.9 % 150 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin (VANCOCIN) 750 mg in sodium chloride 0.9 % 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin 1,250 mg in sodium chloride 0.9% 250 mL IVPB' THEN cellvaluenumeric 
WHEN celllabel = 'Volume (mL)-vancomycin 1,500 mg in sodium chloride 0.9% 250 mL IVPB' THEN cellvaluenumeric 
END) AS total_volume_ml_day1
FROM
    `physionet-data.eicu_crd.intakeoutput`
WHERE
    intakeoutputoffset BETWEEN -6*60 AND 24*60
GROUP BY
  patientunitstayid      